package org.motechproject.nms.swc.domain;

public enum RejectionReasons {

    INVALID_LOCATION,
    MOBILE_NUMBER_ALREADY_IN_USE,
    UPDATED_RECORD_ALREADY_EXISTS,
    FLW_IMPORT_ERROR,
    INVALID_LMP_DATE,
    INVALID_CASE_NO,
    GF_STATUS_INACTIVE,
    MOBILE_NUMBER_ALREADY_SUBSCRIBED,
    ALREADY_SUBSCRIBED,
    DUPLICATE_MOBILE_NUMBER_IN_DATASET,
    MOBILE_NUMBER_EMPTY_OR_WRONG_FORMAT,
    GF_STATUS_EMPTY_OR_WRONG_FORMAT,
    FIELD_NOT_PRESENT
}
